obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

obj-$(CONFIG_BATTERY_GOOGLE)	+= battery/
obj-$(CONFIG_NTC_GOOGLE)	+= battery/
obj-$(CONFIG_WLC_HL6111R)	+= wlc/
