#
# Makefile for the Novatek NT38350 touchscreen driver.
#

# Each configuration option enables a list of files.

touch_nt38350-y := nt38350.o nt38350_fw_update.o nt38350_ext_proc.o nt38350_mp_ctrlram.o

obj-$(CONFIG_TOUCHSCREEN_NT38350) += touch_nt38350.o
